### ISSUE TITLE
Classic Compat things

### ISSUE THREAD

**Issue by Speiger** [Reoseah/Reinforcement#1]
If you do not aim for classic compat close it directly just want to point things out.
Also i rather take a compat then importing another mod into classic...

But here is a list:
https://github.com/Reoseah/Reinforcement/blob/master/src/main/java/reinforcement/common/config/ConfigRecipes.java#L36
In this class you do a lot of core access while you do not need to do that. There is a Block/Item accessAPI in the API. 

https://github.com/Reoseah/Reinforcement/blob/master/src/main/java/reinforcement/common/block/basic/BlockBasicGlass.java#L49
Yeah you make a cast check why dont you make is this block the block i got from the API and is the block not Opaice and then you have your validation.
Or if you want to make a exact check exp its 1 Block in classic its a block with a meta of 1.

That is everything what needs to be changed to make it classic compatible. If you are not interested in doing that (by closing it and i do not see a push or something like that) then i will use your perm to import the mod (not everything)

**Comment by Reoseah** [comment]
Should be fixed in develop branch now.

**Comment by Speiger** [comment]
Validated!

**Comment by Speiger** [comment]
Just a question why do you spawn so many blocks for the new decorative blocks? I mean the chiseled blocks could be all 1 BlockID instead of the amount you are adding... Just want to understand that...

**Comment by Reoseah** [comment]
@Speiger Yep, I understand, the modders are used to pack everything inside one block... But reasons for this are no longer actual. And having simple blocks without subtypes is just a lot simpler.

**Comment by Speiger** [comment]
@Reoseah you are in this case wrong. The BlockID Limit of 4096 BlockIDs is still there even so block IDs technially do not exist anymore but you can only add so many blocks. So do not think that this has changed!

**Comment by Reoseah** [comment]
@Speiger 4096 blocks is about 100 mods adding 40 blocks each... I think it's hard to exceed it.

**Comment by Speiger** [comment]
@Reoseah xD Mods like Biomes o Plenty add like 100 Blocks (each block has his own id) if you get a lot of mods like these its not far away from using up all ids.
But it does not mean if that you have to do it just wanted to warn... Not more not less
